version: '3'

services:
  web:
    build: . 
    image: basic-ionic
    env_file: .env
    volumes:
      - .:/ionic-app
    working_dir: /ionic-app
    entrypoint: /ionic-app/entrypoint.sh 
    ports:
      - 8100:8100
